/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import ArquivoDAO.ClasseAgendamentoDAO;
import Controlador.ControladorVisualizador;

/**
 *
 * @author felipe_pereira11
 */
public class VisuAgendamentos extends javax.swing.JFrame {

    private final ControladorVisualizador visualizador;
    ClasseAgendamentoDAO agendamento = new ClasseAgendamentoDAO();
    public VisuAgendamentos() {
        initComponents();
        visualizador = new ControladorVisualizador(this);
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoBranco = new javax.swing.JPanel();
        Agendamento = new javax.swing.JLabel();
        FecharAgendamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAgendamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FundoBranco.setBackground(new java.awt.Color(255, 255, 255));
        FundoBranco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agendamento.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Agendamento.setForeground(new java.awt.Color(0, 224, 255));
        Agendamento.setText("AGENDAMENTOS");
        FundoBranco.add(Agendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        FecharAgendamento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        FecharAgendamento.setForeground(new java.awt.Color(0, 224, 255));
        FecharAgendamento.setText("Fechar");
        FecharAgendamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 224, 255)));
        FecharAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharAgendamentoActionPerformed(evt);
            }
        });
        FundoBranco.add(FecharAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 180, 30));

        TabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Obs", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaAgendamento);

        FundoBranco.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 2020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FundoBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 2420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharAgendamentoActionPerformed
        visualizador.entrarPrincipal();
    }//GEN-LAST:event_FecharAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisuAgendamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agendamento;
    private javax.swing.JButton FecharAgendamento;
    private javax.swing.JPanel FundoBranco;
    private javax.swing.JTable TabelaAgendamento;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
